kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: crossp-loc1-hom
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.k8s.io"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.k8s.io".tls]
      insecure_skip_verify = true
nodes:
- role: control-plane
  image: kindest/node:v1.31.1
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        system-reserved: "cpu=300m,memory=5Mi,ephemeral-storage=1Gi"
        kube-reserved: "cpu=200m,memory=5Mi,ephemeral-storage=1Gi"
        eviction-hard: "memory.available<1Gi,nodefs.available<10%"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP