apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - ProviderConfigUsage
  accounts.provider-argocd: apiKey
  # repositories: |
  #   - url: https://charts.crossplane.io/stable
  #     name: crossplane-stable
  #     insecure: true