apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds